### ISSUE TITLE
output file missing in JSON mode with output file suffix ".json"

### ISSUE THREAD

**Issue by okworx** [OndraZizka/csv-cruncher#32]
**Describe the bug**

When I specify an output file using the `-out` parameter which has the suffix `.json`, no output file is written. When omitting the suffix, it works as expected.

**To Reproduce**
1. any input data
2. `./crunch -in example.csv -out result.json --json -sql 'SELECT * FROM example'`
3. no result.json is written

**Expected behavior**
I would expect that a file result.json would be written. 

Interestingly, when omitting the suffix:
`./crunch -in example.csv -out result --json -sql 'SELECT * FROM example'`
a file result.json is written.

**Screenshots / logs**
n/a

**Desktop (please complete the following information):**
 - CsvCruncher version `1.13.0`
 - macOS 10.13.6
 - Java version: `1.8.0_161`

**Additional context**

**Comment by OndraZizka** [comment]
Interesting, I'll have a look in about a month, should be easy to fix. Thanks for reporting.

**Comment by OndraZizka** [comment]
I've changed the processing of parameters and the logic of files creation significantly since this was reported.
There's a test for this scenario which works - `singleImportSingleExport_jsonFileExtension`.

Therefore, closing. Thanks @okworx for reporting.
