### ISSUE TITLE
ERROR App: CSV Cruncher failed: CSV file not found: crunch

### ISSUE THREAD

**Issue by datamaskin** [OndraZizka/csv-cruncher#33]
Attempts to recreate the example: 

> Data and usage example
fails

**To Reproduce**
1. eapData.csv
2. java -jar ../../../../../../dev/csv-cruncher-1.13.1/target/csv-cruncher-1.13.0-single.jar crunch -in ./eapData.csv -out ./results.csv -sql 'SELECT jobName, buildNumber, config, ar, arFile, deployDur, warmupDur, scale, CAST(warmupDur AS DOUBLE) / CAST(deployDur AS DOUBLE) AS warmupSlower FROM eapData ORDER BY deployDur'
3. ERROR App: CSV Cruncher failed: CSV file not found: crunch

**Expected behavior**
A csv file: results.csv

**Desktop (please complete the following information):**
 - csv-cruncher-1.13.1
 - Windows 7  enteprise
 - Java version: java version "1.8.0_231"

**Additional context**
08:17:49 DEBUG App:  Parameters:
08:17:49 DEBUG App:  * crunch
08:17:49 DEBUG App:  * -in
08:17:49 DEBUG App:  * ./eapData.csv
08:17:49 DEBUG App:  * -out
08:17:49 DEBUG App:  * ./results.csv
08:17:49 DEBUG App:  * -sql
08:17:49 DEBUG App:  * SELECT jobName, buildNumber, config, ar, arFile, deployDur, warmupDur, scale, CAST(warmupDur AS DOUBLE) / CAST(deployDur AS DOUBLE) AS warmupSlower FROM eapData ORDER BY deployDur
08:17:49 INFO App: Options:
    dbPath: null
    inputPaths: [crunch, ./eapData.csv]
    includePathsRegex: null
    excludePathsRegex: null
    outputPathCsv: ./results.csv
    queryPerInputSubpart: false
    overwrite: false
    sql: SELECT jobName, buildNumber, config, ar, arFile, deployDur, warmupDur, scale, CAST(warmupDur AS DOUBLE) / CAST(deployDur AS DOUBLE) AS warmupSlower FROM eapData ORDER BY deployDur
    ignoreLineRegex: null
    ignoreFirstLines: 1
    sortInputPaths: PARAMS_ORDER
    sortInputFileGroups: ALPHA
    combineInputFiles: NONE
    combineDirs: COMBINE_PER_EACH_DIR
    initialRowNumber: null
    jsonExportFormat: NONE
    skipNonReadable: false
08:17:49 ERROR App: CSV Cruncher failed: CSV file not found: crunch
java.io.FileNotFoundException: CSV file not found: crunch
        at cz.dynawest.csvcruncher.Options.validate(Options.java:79)

**Comment by OndraZizka** [comment]
I think that the `crunch` part here is not necessary:

`crunch` is the convenience script to skip calling `java -jar ...`

When using `java -jar`, the first parameter is considered as an input, where `-in` is ommited.

Please try without `crunch` and let me know if it worked as expected.

Anyway. I am considering removing the possibility not to use `-in`, because it makes the logic of the parameters too complicated (for the users). Also, `-in very-long-file-name.csv as alias` is coming, and that would make it even more confusing.

**Comment by OndraZizka** [comment]
Updated the README to explicitly mention that `crunch` is a script that calls `java -jar ...`.
